### ISSUE TITLE
Not accept strings value > 10 length

### ISSUE THREAD

**Issue by ednilsonamaral** [jaysvoboda/nodejs-aes256#4]
Hello, guys! How are you?

I found a little problem with this plugin. When I recieve from my API a string with 10 or more values length, the plugin return this error: **RangeError: Uncaught error: Invalid typed array length**.

The string what I receive was **9987443366779988**.

Anybody found that too? Or any sugestion for a fix that?

Thanks! :smiley:

**Comment by jaysvoboda** [comment]
Hi Ednilson,

I wrote a test case to verify this error, but I am unable to recreate it.

```js
it('can handle strings greater than 10 length', function () {
    var str = '9987443366779988';
    ciphertext = aes256.encrypt(key, str);
    var decrypted = aes256.decrypt(key, ciphertext);
    decrypted.should.equal(str);
});
```

Could you post a code snippet?

Thanks,
Jay
